name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: |
          echo ::add-matcher::.github/eslint.json
          yarn run eslint src test --format=compact
      - run: yarn run prettier --check src test
      - run: yarn test:mocha
      - run: yarn prepublishOnly
      - run: yarn docs:build
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-output-changes
          path: test/output/*-changed.*
