name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm run test:vitest
      - run: pnpm run test:tsc
      - run: pnpm run test:lint
      - run: pnpm run test:prettier
      - run: pnpm run prepublishOnly
      - run: pnpm run docs:build
      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: test-output-changes
          path: test/output/*-changed.*
